version: 0.2

phases:
  pre_build:
    commands:
      - echo Running CI for master
      - echo Logging into Dockerhub
      - docker login --username tezoscommons --password $DH_PASSWORD
  build:
    commands:
      - env
      - git status
      - ./ci.sh

