Gateway:
  Server:
    Port: 8085
  Storage:
    S3: # this config here is actually a minio server
      Region: us-east-1
      Bucket: gatewaydata
      Secret: minioadmin
      Key: minioadmin
      Endpoint: http://localhost:9000
      DisableSSL: true
  Uploads:
    Enabled: true
    MaxSize: 50 # MB

Log:
  Format: text
  File: /tmp/tezos-ipfs.log

PinManagerEnbled: false
PinManager:
  API: localhost:5001

DB:
  Storm: /tmp/storm.db

GatewayEnabled: true


# Tell us about yourserlf <3
# This helps make the admin UI nicer
Identity:
  Name: node1
  Organisation: TezosCommons
  Contact: "@johann on tezos-dev slack"
  Comment: "IPFS rocks"

Admin:
  Host: 127.0.0.1
  Port: 5082

# The Peers: Section of this config file gets reloaded immediately
# if a daemon is running, you do NOT need to restart anything
# if you make changes to this section, you SHOULD check the logs
# to make sure you have no error that makes this file invalid to parse
Peers:

  # If you run a Gateway, auto-cache content from this peers
  CacheFor:
    - 12D3KooWKpNTJYurmMnoVpLaMoiJTKHjYifeMm4BHMpNrgcWpRH2

  # If you run a storage server, auto-pin for these nodes
  # auto-pins can be overwritten
  PinFor:
    - 12D3KooWKpNTJYurmMnoVpLaMoiJTKHjYifeMm4BHMpNrgcWpRH2

  # trust information that comes from these peers and
  # If you run a Gateway, make sure tipfs is conencted to
  TrustedPeers:
    - 12D3KooWKpNTJYurmMnoVpLaMoiJTKHjYifeMm4BHMpNrgcWpRH2
    - 12D3KooWSb2MqWGib529J5vR2nW9FpuNh6L2y71M9zNLwiFPa4ez
    - 12D3KooWK4Typh8no29AF2iCJ5QEDRZAbFrWLavE5v3G1NWQbKwM
    - 12D3KooWP1F2VnTpS9guj9ETnyeUe1eMsreF5XNAhZTkTqVw2m5V
